const vehicleData = [
 {
   "vehicleNumber": "GA11WX2345",
   "chassisNo": "MGOA011OPQR123456",
   "engineNumber": "G37W67890XXXXX",
   "ownerName": "Shivani Kunde",
   "phoneNumber": 8331234567,
   "vehicleClass": "SUV",
   "fuelType": "PETROL",
   "makerModel": "Jeep Compass",
   "vehicleColor": "OLIVE GREEN",
   "seatCapacity": 5,
   "insuranceCompany": "National Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal parking",
   "timestamp": 1681123456,
   "location": "Arambol",
   "officer": "Nikhil Parsekar",
   "challanAmount": 400,
   "longitude": 73.7042,
   "latitude": 15.6845
 },
 {
   "vehicleNumber": "GA16GH2345",
   "chassisNo": "MGOA016JKLM678901",
   "engineNumber": "G42B45678XXXXX",
   "ownerName": "Varun Shirodkar",
   "phoneNumber": 8336789012,
   "vehicleClass": "Compact SUV",
   "fuelType": "PETROL",
   "makerModel": "Renault Kiger",
   "vehicleColor": "YELLOW",
   "seatCapacity": 5,
   "insuranceCompany": "Liberty General Insurance",
   "ownershipDesc": "THIRD OWNER",
   "violations": "Reckless driving",
   "timestamp": 1681678901,
   "location": "Mandrem",
   "officer": "Pooja Dubashi",
   "challanAmount": 800,
   "longitude": 73.7064,
   "latitude": 15.6566
 },
 {
   "vehicleNumber": "GA12YZ6789",
   "chassisNo": "MGOA012STUV456789",
   "engineNumber": "G38X23456XXXXX",
   "ownerName": "Rohan Navelkar",
   "phoneNumber": 8332345678,
   "vehicleClass": "Hatchback",
   "fuelType": "CNG",
   "makerModel": "Hyundai i20",
   "vehicleColor": "BLUE",
   "seatCapacity": 5,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Tailgating",
   "timestamp": 1681234567,
   "location": "Morjim",
   "officer": "Tanvi Shet",
   "challanAmount": 500,
   "longitude": 73.7388,
   "latitude": 15.6297
 },
 {
   "vehicleNumber": "GA17JK6789",
   "chassisNo": "MGOA017NOPQ901234",
   "engineNumber": "G43C01234XXXXX",
   "ownerName": "Deepika Dessai",
   "phoneNumber": 8337890123,
   "vehicleClass": "Sedan",
   "fuelType": "CNG",
   "makerModel": "Tata Tigor",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "Universal Sompo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Wrong parking",
   "timestamp": 1681789012,
   "location": "Chapora",
   "officer": "Siddesh Kerkar",
   "challanAmount": 400,
   "longitude": 73.7391,
   "latitude": 15.6025
 },
 {
   "vehicleNumber": "UP85CD6995",
   "chassisNo": "MAKFC6221LJN0XXXXX",
   "engineNumber": "W16A57458XXXXX",
   "ownerName": "Rohan Gupta",
   "phoneNumber": 8720652304,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Mahindra XUV700",
   "vehicleColor": "BLUE",
   "seatCapacity": 2,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1151296954,
   "location": "Anjuna",
   "officer": "Sanjay Deshmukh",
   "challanAmount": 500,
   "longitude": 73.7437,
   "latitude": 15.5784
 },
 {
   "vehicleNumber": "UP85CD6995",
   "chassisNo": "MAKFC6221LJN0XXXXX",
   "engineNumber": "W16A57458XXXXX",
   "ownerName": "Rohan Gupta",
   "phoneNumber": 8720652304,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Mahindra XUV700",
   "vehicleColor": "BLUE",
   "seatCapacity": 2,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1151296954,
   "location": "Anjuna",
   "officer": "Sanjay Deshmukh",
   "challanAmount": 500,
   "longitude": 73.7437,
   "latitude": 15.5784
 },
 {
   "vehicleNumber": "UP85CD6995",
   "chassisNo": "MAKFC6221LJN0XXXXX",
   "engineNumber": "W16A57458XXXXX",
   "ownerName": "Rohan Gupta",
   "phoneNumber": 8720652304,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Mahindra XUV700",
   "vehicleColor": "BLUE",
   "seatCapacity": 2,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1151296954,
   "location": "Anjuna",
   "officer": "Sanjay Deshmukh",
   "challanAmount": 500,
   "longitude": 73.7437,
   "latitude": 15.5784
 },
 {
   "vehicleNumber": "MH12JK7890",
   "chassisNo": "MDEFG90HIJK123456",
   "engineNumber": "N21E78904XXXXX",
   "ownerName": "Arya Bose",
   "phoneNumber": 7364439792,
   "vehicleClass": "Compact SUV",
   "fuelType": "PETROL",
   "makerModel": "Nissan Magnite",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "Oriental Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal U-turn",
   "timestamp": 1549296966,
   "location": "Vagator",
   "officer": "Meera Banerjee",
   "challanAmount": 300,
   "longitude": 73.7448,
   "latitude": 15.5976
 },
 {
   "vehicleNumber": "MH12JK7890",
   "chassisNo": "MDEFG90HIJK123456",
   "engineNumber": "N21E78904XXXXX",
   "ownerName": "Arya Bose",
   "phoneNumber": 7364439792,
   "vehicleClass": "Compact SUV",
   "fuelType": "PETROL",
   "makerModel": "Nissan Magnite",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "Oriental Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal U-turn",
   "timestamp": 1549296966,
   "location": "Vagator",
   "officer": "Meera Banerjee",
   "challanAmount": 300,
   "longitude": 73.7448,
   "latitude": 15.5976
 },
 {
   "vehicleNumber": "MH12JK7890",
   "chassisNo": "MDEFG90HIJK123456",
   "engineNumber": "N21E78904XXXXX",
   "ownerName": "Arya Bose",
   "phoneNumber": 7364439792,
   "vehicleClass": "Compact SUV",
   "fuelType": "PETROL",
   "makerModel": "Nissan Magnite",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "Oriental Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal U-turn",
   "timestamp": 1549296966,
   "location": "Vagator",
   "officer": "Meera Banerjee",
   "challanAmount": 300,
   "longitude": 73.7448,
   "latitude": 15.5976
 },
 {
   "vehicleNumber": "UP59CD4918",
   "chassisNo": "MAKFC1530LJN0XXXXX",
   "engineNumber": "W16A55514XXXXX",
   "ownerName": "Advika Mehta",
   "phoneNumber": 8254534294,
   "vehicleClass": "SUV",
   "fuelType": "CNG",
   "makerModel": "Tata Harrier",
   "vehicleColor": "BLACK",
   "seatCapacity": 4,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "FOURTH OWNER",
   "violations": "Underage driving",
   "timestamp": 987404067,
   "location": "Calangute",
   "officer": "Deepa Singh",
   "challanAmount": 700,
   "longitude": 73.7545,
   "latitude": 15.5431
 },
 {
   "vehicleNumber": "UP59CD4918",
   "chassisNo": "MAKFC1530LJN0XXXXX",
   "engineNumber": "W16A55514XXXXX",
   "ownerName": "Advika Mehta",
   "phoneNumber": 8254534294,
   "vehicleClass": "SUV",
   "fuelType": "CNG",
   "makerModel": "Tata Harrier",
   "vehicleColor": "BLACK",
   "seatCapacity": 4,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "FOURTH OWNER",
   "violations": "Underage driving",
   "timestamp": 987404067,
   "location": "Calangute",
   "officer": "Deepa Singh",
   "challanAmount": 700,
   "longitude": 73.7545,
   "latitude": 15.5431
 },
 {
   "vehicleNumber": "UP59CD4918",
   "chassisNo": "MAKFC1530LJN0XXXXX",
   "engineNumber": "W16A55514XXXXX",
   "ownerName": "Advika Mehta",
   "phoneNumber": 8254534294,
   "vehicleClass": "SUV",
   "fuelType": "CNG",
   "makerModel": "Tata Harrier",
   "vehicleColor": "BLACK",
   "seatCapacity": 4,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "FOURTH OWNER",
   "violations": "Underage driving",
   "timestamp": 987404067,
   "location": "Calangute",
   "officer": "Deepa Singh",
   "challanAmount": 700,
   "longitude": 73.7545,
   "latitude": 15.5431
 },
 {
   "vehicleNumber": "UP65CD5318",
   "chassisNo": "MAKFC2361LJN0XXXXX",
   "engineNumber": "X16A56706XXXXX",
   "ownerName": "Riya Menon",
   "phoneNumber": 7404724207,
   "vehicleClass": "Three Wheeler",
   "fuelType": "ELECTRIC",
   "makerModel": "TVS King Deluxe",
   "vehicleColor": "BLUE",
   "seatCapacity": 3,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Reckless driving",
   "timestamp": 1101880060,
   "location": "Baga",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.7548,
   "latitude": 15.5656
 },
 {
   "vehicleNumber": "UP65CD5318",
   "chassisNo": "MAKFC2361LJN0XXXXX",
   "engineNumber": "X16A56706XXXXX",
   "ownerName": "Riya Menon",
   "phoneNumber": 7404724207,
   "vehicleClass": "Three Wheeler",
   "fuelType": "ELECTRIC",
   "makerModel": "TVS King Deluxe",
   "vehicleColor": "BLUE",
   "seatCapacity": 3,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Reckless driving",
   "timestamp": 1101880060,
   "location": "Baga",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.7548,
   "latitude": 15.5656
 },
 {
   "vehicleNumber": "UP65CD5318",
   "chassisNo": "MAKFC2361LJN0XXXXX",
   "engineNumber": "X16A56706XXXXX",
   "ownerName": "Riya Menon",
   "phoneNumber": 7404724207,
   "vehicleClass": "Three Wheeler",
   "fuelType": "ELECTRIC",
   "makerModel": "TVS King Deluxe",
   "vehicleColor": "BLUE",
   "seatCapacity": 3,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Reckless driving",
   "timestamp": 1101880060,
   "location": "Baga",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.7548,
   "latitude": 15.5656
 },
 {
   "vehicleNumber": "RJ14ST4567",
   "chassisNo": "MRSTUV78WXYZ901234",
   "engineNumber": "N25J45679XXXXX",
   "ownerName": "Mira Roy",
   "phoneNumber": 9235315307,
   "vehicleClass": "Micro SUV",
   "fuelType": "PETROL",
   "makerModel": "Maruti Suzuki S-Presso",
   "vehicleColor": "ORANGE",
   "seatCapacity": 5,
   "insuranceCompany": "Future Generali",
   "ownershipDesc": "FIRST OWNER",
   "violations": "No driving license",
   "timestamp": 1620203516,
   "location": "Baga",
   "officer": "Sneha Mehta",
   "challanAmount": 700,
   "longitude": 73.7556,
   "latitude": 15.5645
 },
 {
   "vehicleNumber": "RJ14ST4567",
   "chassisNo": "MRSTUV78WXYZ901234",
   "engineNumber": "N25J45679XXXXX",
   "ownerName": "Mira Roy",
   "phoneNumber": 9235315307,
   "vehicleClass": "Micro SUV",
   "fuelType": "PETROL",
   "makerModel": "Maruti Suzuki S-Presso",
   "vehicleColor": "ORANGE",
   "seatCapacity": 5,
   "insuranceCompany": "Future Generali",
   "ownershipDesc": "FIRST OWNER",
   "violations": "No driving license",
   "timestamp": 1620203516,
   "location": "Baga",
   "officer": "Sneha Mehta",
   "challanAmount": 700,
   "longitude": 73.7556,
   "latitude": 15.5645
 },
 {
   "vehicleNumber": "RJ14ST4567",
   "chassisNo": "MRSTUV78WXYZ901234",
   "engineNumber": "N25J45679XXXXX",
   "ownerName": "Mira Roy",
   "phoneNumber": 9235315307,
   "vehicleClass": "Micro SUV",
   "fuelType": "PETROL",
   "makerModel": "Maruti Suzuki S-Presso",
   "vehicleColor": "ORANGE",
   "seatCapacity": 5,
   "insuranceCompany": "Future Generali",
   "ownershipDesc": "FIRST OWNER",
   "violations": "No driving license",
   "timestamp": 1620203516,
   "location": "Baga",
   "officer": "Sneha Mehta",
   "challanAmount": 700,
   "longitude": 73.7556,
   "latitude": 15.5645
 },
 {
   "vehicleNumber": "GA06NP6789",
   "chassisNo": "MGOA007YZAB901234",
   "engineNumber": "G33S45678XXXXX",
   "ownerName": "Neha Vernekar",
   "phoneNumber": 8327890123,
   "vehicleClass": "Electric Car",
   "fuelType": "ELECTRIC",
   "makerModel": "Tata Nexon EV",
   "vehicleColor": "TEAL",
   "seatCapacity": 5,
   "insuranceCompany": "United India Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Lane cutting",
   "timestamp": 1680789012,
   "location": "Pernem",
   "officer": "Aditya Kerkar",
   "challanAmount": 600,
   "longitude": 73.7951,
   "latitude": 15.7217
 },
 {
   "vehicleNumber": "GA06NP6789",
   "chassisNo": "MGOA007YZAB901234",
   "engineNumber": "G33S45678XXXXX",
   "ownerName": "Neha Vernekar",
   "phoneNumber": 8327890123,
   "vehicleClass": "Electric Car",
   "fuelType": "ELECTRIC",
   "makerModel": "Tata Nexon EV",
   "vehicleColor": "TEAL",
   "seatCapacity": 5,
   "insuranceCompany": "United India Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Lane cutting",
   "timestamp": 1680789012,
   "location": "Pernem",
   "officer": "Aditya Kerkar",
   "challanAmount": 600,
   "longitude": 73.7951,
   "latitude": 15.7217
 },
 {
   "vehicleNumber": "DL01CD5678",
   "chassisNo": "MPQRS34TUVW567890",
   "engineNumber": "Y18B56781XXXXX",
   "ownerName": "Nishant Rao",
   "phoneNumber": 7425625678,
   "vehicleClass": "Sedan",
   "fuelType": "CNG",
   "makerModel": "Honda City",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Failure to yield to pedestrians",
   "timestamp": 1208860026,
   "location": "Dona Paula",
   "officer": "Rajesh Kumar",
   "challanAmount": 700,
   "longitude": 73.8034,
   "latitude": 15.4509
 },
 {
   "vehicleNumber": "DL01CD5678",
   "chassisNo": "MPQRS34TUVW567890",
   "engineNumber": "Y18B56781XXXXX",
   "ownerName": "Nishant Rao",
   "phoneNumber": 7425625678,
   "vehicleClass": "Sedan",
   "fuelType": "CNG",
   "makerModel": "Honda City",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Failure to yield to pedestrians",
   "timestamp": 1208860026,
   "location": "Dona Paula",
   "officer": "Rajesh Kumar",
   "challanAmount": 700,
   "longitude": 73.8034,
   "latitude": 15.4509
 },
 {
   "vehicleNumber": "DL01CD5678",
   "chassisNo": "MPQRS34TUVW567890",
   "engineNumber": "Y18B56781XXXXX",
   "ownerName": "Nishant Rao",
   "phoneNumber": 7425625678,
   "vehicleClass": "Sedan",
   "fuelType": "CNG",
   "makerModel": "Honda City",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Failure to yield to pedestrians",
   "timestamp": 1208860026,
   "location": "Dona Paula",
   "officer": "Rajesh Kumar",
   "challanAmount": 700,
   "longitude": 73.8034,
   "latitude": 15.4509
 },
 {
   "vehicleNumber": "MH02AB1234",
   "chassisNo": "MABCD12EFGH345678",
   "engineNumber": "Y17A12348XXXXX",
   "ownerName": "Diya Singh",
   "phoneNumber": 8730089864,
   "vehicleClass": "SUV",
   "fuelType": "PETROL",
   "makerModel": "MG Hector",
   "vehicleColor": "WHITE",
   "seatCapacity": 5,
   "insuranceCompany": "ICICI Lombard",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Using mobile phone while driving",
   "timestamp": 1189998149,
   "location": "Mapusa",
   "officer": "Pooja Reddy",
   "challanAmount": 300,
   "longitude": 73.8098,
   "latitude": 15.5932
 },
 {
   "vehicleNumber": "MH02AB1234",
   "chassisNo": "MABCD12EFGH345678",
   "engineNumber": "Y17A12348XXXXX",
   "ownerName": "Diya Singh",
   "phoneNumber": 8730089864,
   "vehicleClass": "SUV",
   "fuelType": "PETROL",
   "makerModel": "MG Hector",
   "vehicleColor": "WHITE",
   "seatCapacity": 5,
   "insuranceCompany": "ICICI Lombard",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Using mobile phone while driving",
   "timestamp": 1189998149,
   "location": "Mapusa",
   "officer": "Pooja Reddy",
   "challanAmount": 300,
   "longitude": 73.8098,
   "latitude": 15.5932
 },
 {
   "vehicleNumber": "MH02AB1234",
   "chassisNo": "MABCD12EFGH345678",
   "engineNumber": "Y17A12348XXXXX",
   "ownerName": "Diya Singh",
   "phoneNumber": 8730089864,
   "vehicleClass": "SUV",
   "fuelType": "PETROL",
   "makerModel": "MG Hector",
   "vehicleColor": "WHITE",
   "seatCapacity": 5,
   "insuranceCompany": "ICICI Lombard",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Using mobile phone while driving",
   "timestamp": 1189998149,
   "location": "Mapusa",
   "officer": "Pooja Reddy",
   "challanAmount": 300,
   "longitude": 73.8098,
   "latitude": 15.5932
 },
 {
   "vehicleNumber": "GA07AB1234",
   "chassisNo": "MGOA001ABCD123456",
   "engineNumber": "G27L12345XXXXX",
   "ownerName": "Sanjana Naik",
   "phoneNumber": 8322145678,
   "vehicleClass": "Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Maruti Suzuki Baleno",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "New India Assurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Speeding",
   "timestamp": 1680123456,
   "location": "Vasco da Gama",
   "officer": "Pranav Desai",
   "challanAmount": 600,
   "longitude": 73.8113,
   "latitude": 15.3927
 },
 {
   "vehicleNumber": "GA07AB1234",
   "chassisNo": "MGOA001ABCD123456",
   "engineNumber": "G27L12345XXXXX",
   "ownerName": "Sanjana Naik",
   "phoneNumber": 8322145678,
   "vehicleClass": "Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Maruti Suzuki Baleno",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "New India Assurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Speeding",
   "timestamp": 1680123456,
   "location": "Vasco da Gama",
   "officer": "Pranav Desai",
   "challanAmount": 600,
   "longitude": 73.8113,
   "latitude": 15.3927
 },
 {
   "vehicleNumber": "UP44CD4714",
   "chassisNo": "MAKFC1980LJN0XXXXX",
   "engineNumber": "Z16A59304XXXXX",
   "ownerName": "Ishaan Reddy",
   "phoneNumber": 9569516098,
   "vehicleClass": "Tractor",
   "fuelType": "HYBRID",
   "makerModel": "Mahindra Arjun Novo 605 DI",
   "vehicleColor": "BLACK",
   "seatCapacity": 7,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal parking",
   "timestamp": 972546433,
   "location": "Mapusa",
   "officer": "Rahul Gupta",
   "challanAmount": 300,
   "longitude": 73.8123,
   "latitude": 15.5916
 },
 {
   "vehicleNumber": "UP44CD4714",
   "chassisNo": "MAKFC1980LJN0XXXXX",
   "engineNumber": "Z16A59304XXXXX",
   "ownerName": "Ishaan Reddy",
   "phoneNumber": 9569516098,
   "vehicleClass": "Tractor",
   "fuelType": "HYBRID",
   "makerModel": "Mahindra Arjun Novo 605 DI",
   "vehicleColor": "BLACK",
   "seatCapacity": 7,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal parking",
   "timestamp": 972546433,
   "location": "Mapusa",
   "officer": "Rahul Gupta",
   "challanAmount": 300,
   "longitude": 73.8123,
   "latitude": 15.5916
 },
 {
   "vehicleNumber": "UP44CD4714",
   "chassisNo": "MAKFC1980LJN0XXXXX",
   "engineNumber": "Z16A59304XXXXX",
   "ownerName": "Ishaan Reddy",
   "phoneNumber": 9569516098,
   "vehicleClass": "Tractor",
   "fuelType": "HYBRID",
   "makerModel": "Mahindra Arjun Novo 605 DI",
   "vehicleColor": "BLACK",
   "seatCapacity": 7,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Illegal parking",
   "timestamp": 972546433,
   "location": "Mapusa",
   "officer": "Rahul Gupta",
   "challanAmount": 300,
   "longitude": 73.8123,
   "latitude": 15.5916
 },
 {
   "vehicleNumber": "UP32UV8901",
   "chassisNo": "MABCDE90FGHI123456",
   "engineNumber": "N26K89015XXXXX",
   "ownerName": "Kunal Bhatia",
   "phoneNumber": 8576651454,
   "vehicleClass": "MPV",
   "fuelType": "CNG",
   "makerModel": "Toyota Innova Crysta",
   "vehicleColor": "SILVER",
   "seatCapacity": 7,
   "insuranceCompany": "Bharti AXA",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overloaded vehicle",
   "timestamp": 1667279844,
   "location": "Mapusa",
   "officer": "Amit Patel",
   "challanAmount": 1200,
   "longitude": 73.8134,
   "latitude": 15.5923
 },
 {
   "vehicleNumber": "UP32UV8901",
   "chassisNo": "MABCDE90FGHI123456",
   "engineNumber": "N26K89015XXXXX",
   "ownerName": "Kunal Bhatia",
   "phoneNumber": 8576651454,
   "vehicleClass": "MPV",
   "fuelType": "CNG",
   "makerModel": "Toyota Innova Crysta",
   "vehicleColor": "SILVER",
   "seatCapacity": 7,
   "insuranceCompany": "Bharti AXA",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overloaded vehicle",
   "timestamp": 1667279844,
   "location": "Mapusa",
   "officer": "Amit Patel",
   "challanAmount": 1200,
   "longitude": 73.8134,
   "latitude": 15.5923
 },
 {
   "vehicleNumber": "UP32UV8901",
   "chassisNo": "MABCDE90FGHI123456",
   "engineNumber": "N26K89015XXXXX",
   "ownerName": "Kunal Bhatia",
   "phoneNumber": 8576651454,
   "vehicleClass": "MPV",
   "fuelType": "CNG",
   "makerModel": "Toyota Innova Crysta",
   "vehicleColor": "SILVER",
   "seatCapacity": 7,
   "insuranceCompany": "Bharti AXA",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overloaded vehicle",
   "timestamp": 1667279844,
   "location": "Mapusa",
   "officer": "Amit Patel",
   "challanAmount": 1200,
   "longitude": 73.8134,
   "latitude": 15.5923
 },
 {
   "vehicleNumber": "TN04GH3456",
   "chassisNo": "MLMNO78PQRS901234",
   "engineNumber": "N20D34569XXXXX",
   "ownerName": "Kabir Nair",
   "phoneNumber": 7416800040,
   "vehicleClass": "MUV",
   "fuelType": "DIESEL",
   "makerModel": "Maruti Suzuki Ertiga",
   "vehicleColor": "BLACK",
   "seatCapacity": 7,
   "insuranceCompany": "New India Assurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Driving without insurance",
   "timestamp": 1533331911,
   "location": "Mapusa",
   "officer": "Rahul Gupta",
   "challanAmount": 500,
   "longitude": 73.8156,
   "latitude": 15.5898
 },
 {
   "vehicleNumber": "TN04GH3456",
   "chassisNo": "MLMNO78PQRS901234",
   "engineNumber": "N20D34569XXXXX",
   "ownerName": "Kabir Nair",
   "phoneNumber": 7416800040,
   "vehicleClass": "MUV",
   "fuelType": "DIESEL",
   "makerModel": "Maruti Suzuki Ertiga",
   "vehicleColor": "BLACK",
   "seatCapacity": 7,
   "insuranceCompany": "New India Assurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Driving without insurance",
   "timestamp": 1533331911,
   "location": "Mapusa",
   "officer": "Rahul Gupta",
   "challanAmount": 500,
   "longitude": 73.8156,
   "latitude": 15.5898
 },
 {
   "vehicleNumber": "TN04GH3456",
   "chassisNo": "MLMNO78PQRS901234",
   "engineNumber": "N20D34569XXXXX",
   "ownerName": "Kabir Nair",
   "phoneNumber": 7416800040,
   "vehicleClass": "MUV",
   "fuelType": "DIESEL",
   "makerModel": "Maruti Suzuki Ertiga",
   "vehicleColor": "BLACK",
   "seatCapacity": 7,
   "insuranceCompany": "New India Assurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Driving without insurance",
   "timestamp": 1533331911,
   "location": "Mapusa",
   "officer": "Rahul Gupta",
   "challanAmount": 500,
   "longitude": 73.8156,
   "latitude": 15.5898
 },
 {
   "vehicleNumber": "UP36CD5949",
   "chassisNo": "MAKFC8262LJN0XXXXX",
   "engineNumber": "Z16A56792XXXXX",
   "ownerName": "Aarav Sharma",
   "phoneNumber": 9156028226,
   "vehicleClass": "Tractor",
   "fuelType": "DIESEL",
   "makerModel": "John Deere 5050D",
   "vehicleColor": "PLATINUM WHITE",
   "seatCapacity": 6,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Overspeeding",
   "timestamp": 837970847,
   "location": "Panaji",
   "officer": "Sunita Rao",
   "challanAmount": 500,
   "longitude": 73.8245,
   "latitude": 15.4989
 },
 {
   "vehicleNumber": "UP36CD5949",
   "chassisNo": "MAKFC8262LJN0XXXXX",
   "engineNumber": "Z16A56792XXXXX",
   "ownerName": "Aarav Sharma",
   "phoneNumber": 9156028226,
   "vehicleClass": "Tractor",
   "fuelType": "DIESEL",
   "makerModel": "John Deere 5050D",
   "vehicleColor": "PLATINUM WHITE",
   "seatCapacity": 6,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Overspeeding",
   "timestamp": 837970847,
   "location": "Panaji",
   "officer": "Sunita Rao",
   "challanAmount": 500,
   "longitude": 73.8245,
   "latitude": 15.4989
 },
 {
   "vehicleNumber": "UP36CD5949",
   "chassisNo": "MAKFC8262LJN0XXXXX",
   "engineNumber": "Z16A56792XXXXX",
   "ownerName": "Aarav Sharma",
   "phoneNumber": 9156028226,
   "vehicleClass": "Tractor",
   "fuelType": "DIESEL",
   "makerModel": "John Deere 5050D",
   "vehicleColor": "PLATINUM WHITE",
   "seatCapacity": 6,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Overspeeding",
   "timestamp": 837970847,
   "location": "Panaji",
   "officer": "Sunita Rao",
   "challanAmount": 500,
   "longitude": 73.8245,
   "latitude": 15.4989
 },
 {
   "vehicleNumber": "UP49CD4199",
   "chassisNo": "MAKFC8410LJN0XXXXX",
   "engineNumber": "T16A51774XXXXX",
   "ownerName": "Anaya Iyer",
   "phoneNumber": 8052541427,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Hyundai Creta",
   "vehicleColor": "RED",
   "seatCapacity": 2,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Drunk driving",
   "timestamp": 888885179,
   "location": "Panaji",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.8278,
   "latitude": 15.4909
 },
 {
   "vehicleNumber": "UP49CD4199",
   "chassisNo": "MAKFC8410LJN0XXXXX",
   "engineNumber": "T16A51774XXXXX",
   "ownerName": "Anaya Iyer",
   "phoneNumber": 8052541427,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Hyundai Creta",
   "vehicleColor": "RED",
   "seatCapacity": 2,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Drunk driving",
   "timestamp": 888885179,
   "location": "Panaji",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.8278,
   "latitude": 15.4909
 },
 {
   "vehicleNumber": "UP49CD4199",
   "chassisNo": "MAKFC8410LJN0XXXXX",
   "engineNumber": "T16A51774XXXXX",
   "ownerName": "Anaya Iyer",
   "phoneNumber": 8052541427,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Hyundai Creta",
   "vehicleColor": "RED",
   "seatCapacity": 2,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Drunk driving",
   "timestamp": 888885179,
   "location": "Panaji",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.8278,
   "latitude": 15.4909
 },
 {
   "vehicleNumber": "GJ01QR0123",
   "chassisNo": "MJKLM56NOPQ789012",
   "engineNumber": "N24H01231XXXXX",
   "ownerName": "Tara Joshi",
   "phoneNumber": 8944202432,
   "vehicleClass": "Premium Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Tata Altroz",
   "vehicleColor": "WHITE",
   "seatCapacity": 5,
   "insuranceCompany": "SBI General Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Unsafe lane change",
   "timestamp": 1605248166,
   "location": "Panaji",
   "officer": "Deepak Chopra",
   "challanAmount": 500,
   "longitude": 73.8298,
   "latitude": 15.4978
 },
 {
   "vehicleNumber": "GJ01QR0123",
   "chassisNo": "MJKLM56NOPQ789012",
   "engineNumber": "N24H01231XXXXX",
   "ownerName": "Tara Joshi",
   "phoneNumber": 8944202432,
   "vehicleClass": "Premium Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Tata Altroz",
   "vehicleColor": "WHITE",
   "seatCapacity": 5,
   "insuranceCompany": "SBI General Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Unsafe lane change",
   "timestamp": 1605248166,
   "location": "Panaji",
   "officer": "Deepak Chopra",
   "challanAmount": 500,
   "longitude": 73.8298,
   "latitude": 15.4978
 },
 {
   "vehicleNumber": "GJ01QR0123",
   "chassisNo": "MJKLM56NOPQ789012",
   "engineNumber": "N24H01231XXXXX",
   "ownerName": "Tara Joshi",
   "phoneNumber": 8944202432,
   "vehicleClass": "Premium Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Tata Altroz",
   "vehicleColor": "WHITE",
   "seatCapacity": 5,
   "insuranceCompany": "SBI General Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Unsafe lane change",
   "timestamp": 1605248166,
   "location": "Panaji",
   "officer": "Deepak Chopra",
   "challanAmount": 500,
   "longitude": 73.8298,
   "latitude": 15.4978
 },
 {
   "vehicleNumber": "UP78CD1307",
   "chassisNo": "MAKFC3087LJN0XXXXX",
   "engineNumber": "W16A58343XXXXX",
   "ownerName": "Ayaan Kapoor",
   "phoneNumber": 9954151685,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Toyota Fortuner",
   "vehicleColor": "RED",
   "seatCapacity": 7,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Tailgating",
   "timestamp": 1050709951,
   "location": "Panaji",
   "officer": "Rahul Gupta",
   "challanAmount": 500,
   "longitude": 73.8321,
   "latitude": 15.4987
 },
 {
   "vehicleNumber": "UP78CD1307",
   "chassisNo": "MAKFC3087LJN0XXXXX",
   "engineNumber": "W16A58343XXXXX",
   "ownerName": "Ayaan Kapoor",
   "phoneNumber": 9954151685,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Toyota Fortuner",
   "vehicleColor": "RED",
   "seatCapacity": 7,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Tailgating",
   "timestamp": 1050709951,
   "location": "Panaji",
   "officer": "Rahul Gupta",
   "challanAmount": 500,
   "longitude": 73.8321,
   "latitude": 15.4987
 },
 {
   "vehicleNumber": "UP78CD1307",
   "chassisNo": "MAKFC3087LJN0XXXXX",
   "engineNumber": "W16A58343XXXXX",
   "ownerName": "Ayaan Kapoor",
   "phoneNumber": 9954151685,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Toyota Fortuner",
   "vehicleColor": "RED",
   "seatCapacity": 7,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Tailgating",
   "timestamp": 1050709951,
   "location": "Panaji",
   "officer": "Rahul Gupta",
   "challanAmount": 500,
   "longitude": 73.8321,
   "latitude": 15.4987
 },
 {
   "vehicleNumber": "GA05EF9012",
   "chassisNo": "MGOA003IJKL789012",
   "engineNumber": "G29N23456XXXXX",
   "ownerName": "Meera Kamat",
   "phoneNumber": 8323456789,
   "vehicleClass": "Sedan",
   "fuelType": "CNG",
   "makerModel": "Hyundai Aura",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Wrong side driving",
   "timestamp": 1680345678,
   "location": "Bicholim",
   "officer": "Vishal Naik",
   "challanAmount": 800,
   "longitude": 73.9087,
   "latitude": 15.5857
 },
 {
   "vehicleNumber": "GA05EF9012",
   "chassisNo": "MGOA003IJKL789012",
   "engineNumber": "G29N23456XXXXX",
   "ownerName": "Meera Kamat",
   "phoneNumber": 8323456789,
   "vehicleClass": "Sedan",
   "fuelType": "CNG",
   "makerModel": "Hyundai Aura",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "HDFC Ergo",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Wrong side driving",
   "timestamp": 1680345678,
   "location": "Bicholim",
   "officer": "Vishal Naik",
   "challanAmount": 800,
   "longitude": 73.9087,
   "latitude": 15.5857
 },
 {
   "vehicleNumber": "UP13CD5743",
   "chassisNo": "MAKFC4831LJN0XXXXX",
   "engineNumber": "S16A59671XXXXX",
   "ownerName": "Saanvi Deshmukh",
   "phoneNumber": 7564419834,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Kia Seltos",
   "vehicleColor": "SILVER",
   "seatCapacity": 6,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "THIRD OWNER",
   "violations": "No driving license",
   "timestamp": 1017193113,
   "location": "Colva",
   "officer": "Sunita Rao",
   "challanAmount": 700,
   "longitude": 73.9159,
   "latitude": 15.2698
 },
 {
   "vehicleNumber": "UP13CD5743",
   "chassisNo": "MAKFC4831LJN0XXXXX",
   "engineNumber": "S16A59671XXXXX",
   "ownerName": "Saanvi Deshmukh",
   "phoneNumber": 7564419834,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Kia Seltos",
   "vehicleColor": "SILVER",
   "seatCapacity": 6,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "THIRD OWNER",
   "violations": "No driving license",
   "timestamp": 1017193113,
   "location": "Colva",
   "officer": "Sunita Rao",
   "challanAmount": 700,
   "longitude": 73.9159,
   "latitude": 15.2698
 },
 {
   "vehicleNumber": "UP13CD5743",
   "chassisNo": "MAKFC4831LJN0XXXXX",
   "engineNumber": "S16A59671XXXXX",
   "ownerName": "Saanvi Deshmukh",
   "phoneNumber": 7564419834,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Kia Seltos",
   "vehicleColor": "SILVER",
   "seatCapacity": 6,
   "insuranceCompany": "IFFCO Tokio",
   "ownershipDesc": "THIRD OWNER",
   "violations": "No driving license",
   "timestamp": 1017193113,
   "location": "Colva",
   "officer": "Sunita Rao",
   "challanAmount": 700,
   "longitude": 73.9159,
   "latitude": 15.2698
 },
 {
   "vehicleNumber": "GA14CD4567",
   "chassisNo": "MGOA014BCDE012345",
   "engineNumber": "G40Z34567XXXXX",
   "ownerName": "Nikhil Borkar",
   "phoneNumber": 8334567890,
   "vehicleClass": "Two Wheeler",
   "fuelType": "ELECTRIC",
   "makerModel": "Ather 450X",
   "vehicleColor": "WHITE",
   "seatCapacity": 2,
   "insuranceCompany": "Kotak General Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Signal jumping",
   "timestamp": 1681456789,
   "location": "Benaulim",
   "officer": "Shraddha Naik",
   "challanAmount": 600,
   "longitude": 73.9268,
   "latitude": 15.2566
 },
 {
   "vehicleNumber": "KA03EF9012",
   "chassisNo": "MXYZW56ABCD789012",
   "engineNumber": "N19C90121XXXXX",
   "ownerName": "Priya Thakur",
   "phoneNumber": 7487166994,
   "vehicleClass": "Hatchback",
   "fuelType": "ELECTRIC",
   "makerModel": "Maruti Suzuki Swift",
   "vehicleColor": "BLUE",
   "seatCapacity": 5,
   "insuranceCompany": "Tata AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "No helmet",
   "timestamp": 1398603871,
   "location": "Margao",
   "officer": "Jimil mandani",
   "challanAmount": 700,
   "longitude": 73.9578,
   "latitude": 15.2745
 },
 {
   "vehicleNumber": "KA03EF9012",
   "chassisNo": "MXYZW56ABCD789012",
   "engineNumber": "N19C90121XXXXX",
   "ownerName": "Priya Thakur",
   "phoneNumber": 7487166994,
   "vehicleClass": "Hatchback",
   "fuelType": "ELECTRIC",
   "makerModel": "Maruti Suzuki Swift",
   "vehicleColor": "BLUE",
   "seatCapacity": 5,
   "insuranceCompany": "Tata AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "No helmet",
   "timestamp": 1398603871,
   "location": "Margao",
   "officer": "Jimil mandani",
   "challanAmount": 700,
   "longitude": 73.9578,
   "latitude": 15.2745
 },
 {
   "vehicleNumber": "KA03EF9012",
   "chassisNo": "MXYZW56ABCD789012",
   "engineNumber": "N19C90121XXXXX",
   "ownerName": "Priya Thakur",
   "phoneNumber": 7487166994,
   "vehicleClass": "Hatchback",
   "fuelType": "ELECTRIC",
   "makerModel": "Maruti Suzuki Swift",
   "vehicleColor": "BLUE",
   "seatCapacity": 5,
   "insuranceCompany": "Tata AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "No helmet",
   "timestamp": 1398603871,
   "location": "Margao",
   "officer": "Jimil mandani",
   "challanAmount": 700,
   "longitude": 73.9578,
   "latitude": 15.2745
 },
 {
   "vehicleNumber": "UP41CD1468",
   "chassisNo": "MAKFC9295LJN0XXXXX",
   "engineNumber": "A16A53804XXXXX",
   "ownerName": "Vihaan Patel",
   "phoneNumber": 9296320545,
   "vehicleClass": "Three Wheeler",
   "fuelType": "HYBRID",
   "makerModel": "Bajaj RE Compact",
   "vehicleColor": "SILVER",
   "seatCapacity": 6,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "SECOND OWNER",
   "violations": "No helmet",
   "timestamp": 888129109,
   "location": "Margao",
   "officer": "Rajesh Kumar",
   "challanAmount": 700,
   "longitude": 73.9587,
   "latitude": 15.2721
 },
 {
   "vehicleNumber": "UP41CD1468",
   "chassisNo": "MAKFC9295LJN0XXXXX",
   "engineNumber": "A16A53804XXXXX",
   "ownerName": "Vihaan Patel",
   "phoneNumber": 9296320545,
   "vehicleClass": "Three Wheeler",
   "fuelType": "HYBRID",
   "makerModel": "Bajaj RE Compact",
   "vehicleColor": "SILVER",
   "seatCapacity": 6,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "SECOND OWNER",
   "violations": "No helmet",
   "timestamp": 888129109,
   "location": "Margao",
   "officer": "Rajesh Kumar",
   "challanAmount": 700,
   "longitude": 73.9587,
   "latitude": 15.2721
 },
 {
   "vehicleNumber": "UP41CD1468",
   "chassisNo": "MAKFC9295LJN0XXXXX",
   "engineNumber": "A16A53804XXXXX",
   "ownerName": "Vihaan Patel",
   "phoneNumber": 9296320545,
   "vehicleClass": "Three Wheeler",
   "fuelType": "HYBRID",
   "makerModel": "Bajaj RE Compact",
   "vehicleColor": "SILVER",
   "seatCapacity": 6,
   "insuranceCompany": "TATA AIG",
   "ownershipDesc": "SECOND OWNER",
   "violations": "No helmet",
   "timestamp": 888129109,
   "location": "Margao",
   "officer": "Rajesh Kumar",
   "challanAmount": 700,
   "longitude": 73.9587,
   "latitude": 15.2721
 },
 {
   "vehicleNumber": "WB05NP6789",
   "chassisNo": "MBCDE34FGHI567890",
   "engineNumber": "N23G67896XXXXX",
   "ownerName": "Dev Choudhary",
   "phoneNumber": 9737803401,
   "vehicleClass": "Compact Sedan",
   "fuelType": "DIESEL",
   "makerModel": "Honda Amaze",
   "vehicleColor": "BROWN",
   "seatCapacity": 5,
   "insuranceCompany": "Reliance General Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Drunk driving",
   "timestamp": 1601244425,
   "location": "Margao",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.9598,
   "latitude": 15.2734
 },
 {
   "vehicleNumber": "WB05NP6789",
   "chassisNo": "MBCDE34FGHI567890",
   "engineNumber": "N23G67896XXXXX",
   "ownerName": "Dev Choudhary",
   "phoneNumber": 9737803401,
   "vehicleClass": "Compact Sedan",
   "fuelType": "DIESEL",
   "makerModel": "Honda Amaze",
   "vehicleColor": "BROWN",
   "seatCapacity": 5,
   "insuranceCompany": "Reliance General Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Drunk driving",
   "timestamp": 1601244425,
   "location": "Margao",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.9598,
   "latitude": 15.2734
 },
 {
   "vehicleNumber": "WB05NP6789",
   "chassisNo": "MBCDE34FGHI567890",
   "engineNumber": "N23G67896XXXXX",
   "ownerName": "Dev Choudhary",
   "phoneNumber": 9737803401,
   "vehicleClass": "Compact Sedan",
   "fuelType": "DIESEL",
   "makerModel": "Honda Amaze",
   "vehicleColor": "BROWN",
   "seatCapacity": 5,
   "insuranceCompany": "Reliance General Insurance",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Drunk driving",
   "timestamp": 1601244425,
   "location": "Margao",
   "officer": "Rajesh Kumar",
   "challanAmount": 1000,
   "longitude": 73.9598,
   "latitude": 15.2734
 },
 {
   "vehicleNumber": "GA08CD5678",
   "chassisNo": "MGOA002EFGH456789",
   "engineNumber": "G28M67890XXXXX",
   "ownerName": "Rahul Salgaonkar",
   "phoneNumber": 8322987654,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Mahindra Thar",
   "vehicleColor": "GREEN",
   "seatCapacity": 4,
   "insuranceCompany": "ICICI Lombard",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Parking violation",
   "timestamp": 1680234567,
   "location": "Ponda",
   "officer": "Neha Sawant",
   "challanAmount": 400,
   "longitude": 73.9668,
   "latitude": 15.4027
 },
 {
   "vehicleNumber": "GA08CD5678",
   "chassisNo": "MGOA002EFGH456789",
   "engineNumber": "G28M67890XXXXX",
   "ownerName": "Rahul Salgaonkar",
   "phoneNumber": 8322987654,
   "vehicleClass": "SUV",
   "fuelType": "DIESEL",
   "makerModel": "Mahindra Thar",
   "vehicleColor": "GREEN",
   "seatCapacity": 4,
   "insuranceCompany": "ICICI Lombard",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Parking violation",
   "timestamp": 1680234567,
   "location": "Ponda",
   "officer": "Neha Sawant",
   "challanAmount": 400,
   "longitude": 73.9668,
   "latitude": 15.4027
 },
 {
   "vehicleNumber": "GA13AB0123",
   "chassisNo": "MGOA013WXYZ789012",
   "engineNumber": "G39Y78901XXXXX",
   "ownerName": "Aishwarya Gaitonde",
   "phoneNumber": 8333456789,
   "vehicleClass": "Luxury Car",
   "fuelType": "HYBRID",
   "makerModel": "BMW 5 Series",
   "vehicleColor": "BLACK",
   "seatCapacity": 5,
   "insuranceCompany": "Cholamandalam MS",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1681345678,
   "location": "Agonda",
   "officer": "Vikram Prabhu",
   "challanAmount": 1000,
   "longitude": 74.009,
   "latitude": 15.0461
 },
 {
   "vehicleNumber": "UP74CD2372",
   "chassisNo": "MAKFC6037LJN0XXXXX",
   "engineNumber": "X16A56424XXXXX",
   "ownerName": "Arjun Verma",
   "phoneNumber": 8774809210,
   "vehicleClass": "Three Wheeler",
   "fuelType": "HYBRID",
   "makerModel": "Piaggio Ape Xtra LDX",
   "vehicleColor": "BLACK",
   "seatCapacity": 3,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Running a red light",
   "timestamp": 1010791092,
   "location": "Palolem",
   "officer": "Vikram Malhotra",
   "challanAmount": 500,
   "longitude": 74.0221,
   "latitude": 14.9958
 },
 {
   "vehicleNumber": "UP74CD2372",
   "chassisNo": "MAKFC6037LJN0XXXXX",
   "engineNumber": "X16A56424XXXXX",
   "ownerName": "Arjun Verma",
   "phoneNumber": 8774809210,
   "vehicleClass": "Three Wheeler",
   "fuelType": "HYBRID",
   "makerModel": "Piaggio Ape Xtra LDX",
   "vehicleColor": "BLACK",
   "seatCapacity": 3,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Running a red light",
   "timestamp": 1010791092,
   "location": "Palolem",
   "officer": "Vikram Malhotra",
   "challanAmount": 500,
   "longitude": 74.0221,
   "latitude": 14.9958
 },
 {
   "vehicleNumber": "UP74CD2372",
   "chassisNo": "MAKFC6037LJN0XXXXX",
   "engineNumber": "X16A56424XXXXX",
   "ownerName": "Arjun Verma",
   "phoneNumber": 8774809210,
   "vehicleClass": "Three Wheeler",
   "fuelType": "HYBRID",
   "makerModel": "Piaggio Ape Xtra LDX",
   "vehicleColor": "BLACK",
   "seatCapacity": 3,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Running a red light",
   "timestamp": 1010791092,
   "location": "Palolem",
   "officer": "Vikram Malhotra",
   "challanAmount": 500,
   "longitude": 74.0221,
   "latitude": 14.9958
 },
 {
   "vehicleNumber": "TS10LM2345",
   "chassisNo": "MSTUW12VWXY345678",
   "engineNumber": "B22F23457XXXXX",
   "ownerName": "Naina Agarwal",
   "phoneNumber": 8031549089,
   "vehicleClass": "Luxury Sedan",
   "fuelType": "HYBRID",
   "makerModel": "Mercedes-Benz C-Class",
   "vehicleColor": "GREY",
   "seatCapacity": 5,
   "insuranceCompany": "United India Insurance",
   "ownershipDesc": "THIRD OWNER",
   "violations": "Not wearing a seatbelt",
   "timestamp": 1560119030,
   "location": "Palolem",
   "officer": "Sanjay Deshmukh",
   "challanAmount": 300,
   "longitude": 74.0234,
   "latitude": 14.9967
 },
 {
   "vehicleNumber": "TS10LM2345",
   "chassisNo": "MSTUW12VWXY345678",
   "engineNumber": "B22F23457XXXXX",
   "ownerName": "Naina Agarwal",
   "phoneNumber": 8031549089,
   "vehicleClass": "Luxury Sedan",
   "fuelType": "HYBRID",
   "makerModel": "Mercedes-Benz C-Class",
   "vehicleColor": "GREY",
   "seatCapacity": 5,
   "insuranceCompany": "United India Insurance",
   "ownershipDesc": "THIRD OWNER",
   "violations": "Not wearing a seatbelt",
   "timestamp": 1560119030,
   "location": "Palolem",
   "officer": "Sanjay Deshmukh",
   "challanAmount": 300,
   "longitude": 74.0234,
   "latitude": 14.9967
 },
 {
   "vehicleNumber": "TS10LM2345",
   "chassisNo": "MSTUW12VWXY345678",
   "engineNumber": "B22F23457XXXXX",
   "ownerName": "Naina Agarwal",
   "phoneNumber": 8031549089,
   "vehicleClass": "Luxury Sedan",
   "fuelType": "HYBRID",
   "makerModel": "Mercedes-Benz C-Class",
   "vehicleColor": "GREY",
   "seatCapacity": 5,
   "insuranceCompany": "United India Insurance",
   "ownershipDesc": "THIRD OWNER",
   "violations": "Not wearing a seatbelt",
   "timestamp": 1560119030,
   "location": "Palolem",
   "officer": "Sanjay Deshmukh",
   "challanAmount": 300,
   "longitude": 74.0234,
   "latitude": 14.9967
 },
 {
   "vehicleNumber": "GA01LM2345",
   "chassisNo": "MGOA006UVWX678901",
   "engineNumber": "G32R90123XXXXX",
   "ownerName": "Ajit Mandrekar",
   "phoneNumber": 8326789012,
   "vehicleClass": "Luxury Sedan",
   "fuelType": "HYBRID",
   "makerModel": "Lexus ES",
   "vehicleColor": "BLACK",
   "seatCapacity": 5,
   "insuranceCompany": "SBI General Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Red light violation",
   "timestamp": 1680678901,
   "location": "Canacona",
   "officer": "Sonia Dessai",
   "challanAmount": 1000,
   "longitude": 74.0593,
   "latitude": 14.9959
 },
 {
   "vehicleNumber": "GA01LM2345",
   "chassisNo": "MGOA006UVWX678901",
   "engineNumber": "G32R90123XXXXX",
   "ownerName": "Ajit Mandrekar",
   "phoneNumber": 8326789012,
   "vehicleClass": "Luxury Sedan",
   "fuelType": "HYBRID",
   "makerModel": "Lexus ES",
   "vehicleColor": "BLACK",
   "seatCapacity": 5,
   "insuranceCompany": "SBI General Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "Red light violation",
   "timestamp": 1680678901,
   "location": "Canacona",
   "officer": "Sonia Dessai",
   "challanAmount": 1000,
   "longitude": 74.0593,
   "latitude": 14.9959
 },
 {
   "vehicleNumber": "GA09ST4567",
   "chassisNo": "MGOA009GHIJ567890",
   "engineNumber": "G35U56789XXXXX",
   "ownerName": "Lata Naik",
   "phoneNumber": 8329012345,
   "vehicleClass": "Premium Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Volkswagen Polo",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "Future Generali",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1680901234,
   "location": "Quepem",
   "officer": "Mahesh Velip",
   "challanAmount": 800,
   "longitude": 74.0777,
   "latitude": 15.2126
 },
 {
   "vehicleNumber": "GA09ST4567",
   "chassisNo": "MGOA009GHIJ567890",
   "engineNumber": "G35U56789XXXXX",
   "ownerName": "Lata Naik",
   "phoneNumber": 8329012345,
   "vehicleClass": "Premium Hatchback",
   "fuelType": "PETROL",
   "makerModel": "Volkswagen Polo",
   "vehicleColor": "RED",
   "seatCapacity": 5,
   "insuranceCompany": "Future Generali",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1680901234,
   "location": "Quepem",
   "officer": "Mahesh Velip",
   "challanAmount": 800,
   "longitude": 74.0777,
   "latitude": 15.2126
 },
 {
   "vehicleNumber": "GA15EF8901",
   "chassisNo": "MGOA015FGHI345678",
   "engineNumber": "G41A90123XXXXX",
   "ownerName": "Sonali Khandeparkar",
   "phoneNumber": 8335678901,
   "vehicleClass": "MUV",
   "fuelType": "DIESEL",
   "makerModel": "Kia Carens",
   "vehicleColor": "MAROON",
   "seatCapacity": 7,
   "insuranceCompany": "Magma HDI",
   "ownershipDesc": "SECOND OWNER",
   "violations": "No seatbelt",
   "timestamp": 1681567890,
   "location": "Cuncolim",
   "officer": "Amey Naik",
   "challanAmount": 300,
   "longitude": 74.1054,
   "latitude": 15.1766
 },
 {
   "vehicleNumber": "GA10GH3456",
   "chassisNo": "MGOA004MNOP012345",
   "engineNumber": "G30P78901XXXXX",
   "ownerName": "Vivek Parsekar",
   "phoneNumber": 8324567890,
   "vehicleClass": "MUV",
   "fuelType": "DIESEL",
   "makerModel": "Toyota Innova Crysta",
   "vehicleColor": "WHITE",
   "seatCapacity": 7,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "THIRD OWNER",
   "violations": "No pollution certificate",
   "timestamp": 1680456789,
   "location": "Curchorem",
   "officer": "Anjali Borkar",
   "challanAmount": 500,
   "longitude": 74.1109,
   "latitude": 15.2644
 },
 {
   "vehicleNumber": "GA10GH3456",
   "chassisNo": "MGOA004MNOP012345",
   "engineNumber": "G30P78901XXXXX",
   "ownerName": "Vivek Parsekar",
   "phoneNumber": 8324567890,
   "vehicleClass": "MUV",
   "fuelType": "DIESEL",
   "makerModel": "Toyota Innova Crysta",
   "vehicleColor": "WHITE",
   "seatCapacity": 7,
   "insuranceCompany": "Bajaj Allianz",
   "ownershipDesc": "THIRD OWNER",
   "violations": "No pollution certificate",
   "timestamp": 1680456789,
   "location": "Curchorem",
   "officer": "Anjali Borkar",
   "challanAmount": 500,
   "longitude": 74.1109,
   "latitude": 15.2644
 },
 {
   "vehicleNumber": "GA03JK7890",
   "chassisNo": "MGOA005QRST345678",
   "engineNumber": "G31Q34567XXXXX",
   "ownerName": "Pooja Bandodkar",
   "phoneNumber": 8325678901,
   "vehicleClass": "Compact SUV",
   "fuelType": "PETROL",
   "makerModel": "Kia Sonet",
   "vehicleColor": "BLUE",
   "seatCapacity": 5,
   "insuranceCompany": "Tata AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1680567890,
   "location": "Valpoi",
   "officer": "Rohit Gaonkar",
   "challanAmount": 700,
   "longitude": 74.1367,
   "latitude": 15.5321
 },
 {
   "vehicleNumber": "GA03JK7890",
   "chassisNo": "MGOA005QRST345678",
   "engineNumber": "G31Q34567XXXXX",
   "ownerName": "Pooja Bandodkar",
   "phoneNumber": 8325678901,
   "vehicleClass": "Compact SUV",
   "fuelType": "PETROL",
   "makerModel": "Kia Sonet",
   "vehicleColor": "BLUE",
   "seatCapacity": 5,
   "insuranceCompany": "Tata AIG",
   "ownershipDesc": "FIRST OWNER",
   "violations": "Overspeeding",
   "timestamp": 1680567890,
   "location": "Valpoi",
   "officer": "Rohit Gaonkar",
   "challanAmount": 700,
   "longitude": 74.1367,
   "latitude": 15.5321
 },
 {
   "vehicleNumber": "GA02QR0123",
   "chassisNo": "MGOA008CDEF234567",
   "engineNumber": "G34T01234XXXXX",
   "ownerName": "Sunil Chodankar",
   "phoneNumber": 8328901234,
   "vehicleClass": "Two Wheeler",
   "fuelType": "PETROL",
   "makerModel": "Honda Activa",
   "vehicleColor": "GREY",
   "seatCapacity": 2,
   "insuranceCompany": "Oriental Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "No helmet",
   "timestamp": 1680890123,
   "location": "Sanguem",
   "officer": "Reshma Gaude",
   "challanAmount": 300,
   "longitude": 74.151,
   "latitude": 15.2292
 },
 {
   "vehicleNumber": "GA02QR0123",
   "chassisNo": "MGOA008CDEF234567",
   "engineNumber": "G34T01234XXXXX",
   "ownerName": "Sunil Chodankar",
   "phoneNumber": 8328901234,
   "vehicleClass": "Two Wheeler",
   "fuelType": "PETROL",
   "makerModel": "Honda Activa",
   "vehicleColor": "GREY",
   "seatCapacity": 2,
   "insuranceCompany": "Oriental Insurance",
   "ownershipDesc": "SECOND OWNER",
   "violations": "No helmet",
   "timestamp": 1680890123,
   "location": "Sanguem",
   "officer": "Reshma Gaude",
   "challanAmount": 300,
   "longitude": 74.151,
   "latitude": 15.2292
 },
 {
   "vehicleNumber": "GA04UV8901",
   "chassisNo": "MGOA010KLMN890123",
   "engineNumber": "G36V12345XXXXX",
   "ownerName": "Prakash Raikar",
   "phoneNumber": 8320123456,
   "vehicleClass": "Compact Sedan",
   "fuelType": "DIESEL",
   "makerModel": "Maruti Suzuki Dzire",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "Reliance General Insurance",
   "ownershipDesc": "THIRD OWNER",
   "violations": "Dangerous driving",
   "timestamp": 1681012345,
   "location": "Dharbandora",
   "officer": "Sakshi Gawas",
   "challanAmount": 900,
   "longitude": 74.207,
   "latitude": 15.4226
 },
 {
   "vehicleNumber": "GA04UV8901",
   "chassisNo": "MGOA010KLMN890123",
   "engineNumber": "G36V12345XXXXX",
   "ownerName": "Prakash Raikar",
   "phoneNumber": 8320123456,
   "vehicleClass": "Compact Sedan",
   "fuelType": "DIESEL",
   "makerModel": "Maruti Suzuki Dzire",
   "vehicleColor": "SILVER",
   "seatCapacity": 5,
   "insuranceCompany": "Reliance General Insurance",
   "ownershipDesc": "THIRD OWNER",
   "violations": "Dangerous driving",
   "timestamp": 1681012345,
   "location": "Dharbandora",
   "officer": "Sakshi Gawas",
   "challanAmount": 900,
   "longitude": 74.207,
   "latitude": 15.4226
 }
]

export default vehicleData